services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devlink
      MYSQL_USER: devlink_user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=devlink
      - DB_USERNAME=devlink_user
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
    networks:
      - backend
    depends_on:
      - mysql
      - redis

  node:
    image: node:20
    privileged: true
    container_name: node_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: >
      sh -c "echo fs.inotify.max_user_watches=524288 >> /etc/sysctl.conf
      && sysctl -p
      && npm install
      && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - backend

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - backend
    depends_on:
      - app
      - reverb

  reverb:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: laravel_reverb
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
      - BROADCAST_DRIVER=reverb
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=devlink
      - DB_USERNAME=devlink_user
      - DB_PASSWORD=secret
      - REVERB_APP_ID=707813
      - REVERB_APP_KEY=kthmg3yuzm809ipzncae
      - REVERB_APP_SECRET=fzelmm9eg2mg9nrqowcp
      - REVERB_SERVER_HOST=0.0.0.0
      - REVERB_HOST=0.0.0.0
    ports:
      - "8080:8080"
    command: >
      sh -c "php artisan reverb:start & php artisan queue:work"
    networks:
      - backend
    depends_on:
      - mysql

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

networks:
  backend:
    external: true
    
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local